src/Chirp/Controllers/Web/AppController.cs
using AutoMapper;
using Chirp.Database;
using Chirp.Models;
using Chirp.ViewModels;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Net;
using Chirp.PageModels;

namespace Chirp.Controllers.Web
{
    [Route("[action]")]
    public class AppController : Controller
    {
        private UserManager<ChirpUser> m_userManager;

        public AppController(UserManager<ChirpUser> a_userManager)
        {
            m_userManager = a_userManager;
        }

        [Authorize]
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [Authorize]
        public IActionResult Signout()
        {
            return View();
        }

        [Authorize]
        [Route("/user/{userName}")]
        [ActionName("user")]
        public async Task<IActionResult> Users(string userName)
        {
            var userFound = await m_userManager.FindByNameAsync(userName);
            if (userFound == null)
            {
                return new HttpNotFoundResult();
            }
            var userViewModel = Mapper.Map<ChirpUserViewModel>(userFound);
            return View("User", userViewModel);
        }

        [Authorize]
        public async Task<IActionResult> MyAccount(string actionTaken)
        {
            var user = await m_userManager.FindByIdAsync(User.GetUserId());
            var userViewModel = Mapper.Map<ChirpUserViewModel>(user);

            AccountSettingsPageModel pageModel = new AccountSettingsPageModel();
            pageModel.SetMessage(actionTaken);
            pageModel.UserVM = userViewModel;

            return View(pageModel);
        }
    }
}

src/Chirp/Views/Shared/_Layout.cshtml
@using System.Security.Claims

<!DOCTYPE html>
<html>
<head>
    <title>Chirp - @ViewBag.Title</title>
    <base href="/">
    <meta charset="utf-8" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/Paradeiser/dist/min/paradeiser.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-bootstrap/ui-bootstrap.min.js"></script>
    <script src="~/js/directives/chirpControls.js"></script>
    <script src="~/js/directives/simpleControls.js"></script>
    <script src="~/js/app-chirp.js"></script>
</head>
<body>
    <nav class="paradeiser">
        <a asp-controller="App" asp-action="Index">
            <img src="favicon.ico" alt="Logo" class="paradeiser_logo">
            <span>Chirp</span>
        </a>
        <a asp-controller="App" asp-action="About">
            <div class="paradeiser_icon_canvas">
                <i class="fa fa-info-circle fa-3x"></i>
            </div>
            <span>About</span>
        </a>

        <a asp-controller="App" asp-action="Contact">
            <div class="paradeiser_icon_canvas">
                <i class="fa fa-question-circle fa-3x"></i>
            </div>
            <span>Contact</span>
        </a>

        @if (User.IsSignedIn())
        {
            <a href="/user/@User.Identity.Name">
                <div class="paradeiser_icon_canvas">
                    <img src="image/profilepicture/@User.Identity.Name" class="profilepicture paradeiser_logo" alt="Profile Picture" />
                </div>
                <span>@User.Identity.Name</span>
            </a>

        <!-- and include the dropdown aswell -->
            <span class="paradeiser_dropdown">
                <a href="#paradeiser-more" id="paradeiser-dropdown">
                    <div class="paradeiser_icon_canvas">
                        <i class="fa fa-cog fa-3x"></i>
                    </div>
                    <span>More</span>
                </a>
                <ul class="paradeiser_children" id="paradeiser-more">
                    <li><a asp-controller="App" asp-action="MyAccount">Account Settings</a></li>
                    <li><a asp-controller="App" asp-action="Signout">Signout</a></li>
                    <li id="greybox"><a href="#!"></a></li>
                </ul>
            </span>
        }
        else
        {
            <a asp-controller="Auth" asp-action="Login">
                <div class="paradeiser_icon_canvas">
                    <i class="fa fa-sign-in fa-3x"></i>
                </div>
                <span>Login</span>
            </a>

            <a asp-controller="Auth" asp-action="Signup">
                <div class="paradeiser_icon_canvas">
                    <i class="fa fa-level-up fa-3x"></i>
                </div>
                <span>Signup</span>
            </a>
        }
    </nav>

    <div class="container body-content" ng-app="app-chirp">
        @RenderBody()
        <hr />
    </div>
    @RenderSection("Scripts", false)

    <script src="//cdnjs.cloudflare.com/ajax/libs/headroom/0.7.0/headroom.min.js"></script>
    <script src="~/js/navbar.js"></script>
</body>
</html>